language: crystal

os:
  - linux
  - osx

before_script: |
  make clean
  make clobber
  make crun
  make format
  make help
  mkdir -p "${HOME}/bin"
  PREFIX="${HOME}" make install
  make release
  make todo
  PREFIX="${HOME}" sudo make uninstall

script:
  - make check
  - make spec
