language: crystal

crystal:
  - latest

dist: focal

os:
  - linux
  # FIXME: macOS 10.13 error: crystal: no bottle available!
  # - osx

script:
  - make help
  - make todo
  - make tests
  - make clobber
  - make release
  - make sign
  - mkdir -p ./bin
  - PREFIX=. make install
  - PREFIX=. make uninstall
