language: crystal

os:
  - linux
  - osx

script:
  - make clean
  - make clobber
  - make format
  - make crun
  - make help
  - mkdir -p ./bin
  - PREFIX=. make install
  - make release
  - make todo
  - PREFIX=. make uninstall
  - make check
  - make spec
