---
version: 2.1

jobs:
  test:
    docker:
      - image: crystallang/crystal:latest
    steps:
      - checkout
      - run: make help
      - run: make todo
      - run: make tests
      - run: make clobber
      - run: make release
      - run: make sign
      - run: mkdir -p ./bin
      - run: PREFIX=. make install
      - run: PREFIX=. make uninstall

workflows:
  version: 2
  ci:
    jobs:
      - test
...
